services:
  github-runner:

    build:
      context: ./.github/runner

    container_name: github-runner-1
    restart: unless-stopped

    environment:
      GITHUB_REPO: "https://github.com/lehtici4/MedMatch"
      RUNNER_TOKEN: "${RUNNER_TOKEN:?RUNNER_TOKEN nao informado}"
      RUNNER_NAME: "medmatch-runner-1"
      RUNNER_LABELS: "self-hosted,linux,docker,medmatch,devsecops"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock